spring.application.name=Institute

server.port = 8085

Spring.datasource.url=jdbc:mysql://localhost:3306/Project
spring.datasource.username=root
spring.datasource.password=Pratiksha@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


jwt.secret = your256bitsecretkeyhereminimum32characterslong
